export const employees = [
    {
        firstName: 'John',
        lastName: 'Doe',
        birthDate: '12/18/2000',
        startDate: '5/24/2020',
        address: {
            street: 'Fleet street',
            city: 'Orlando',
            stateName: 'AL',
            zipCode: '15897',
        },
        department: 'Sales',
    },
    {
        firstName: 'Bill',
        lastName: 'Nath',
        birthDate: '12/18/1986',
        startDate: '5/24/2016',
        address: {
            street: 'Carnagy square',
            city: 'Bilder',
            stateName: 'KS',
            zipCode: '23645',
        },
        department: 'Engineering',
    },
    {
        firstName: 'Susette',
        lastName: 'Kay',
        birthDate: '10/5/1975',
        startDate: '3/18/1997',
        address: {
            street: 'Bind street',
            city: 'Newyork City',
            stateName: 'NY',
            zipCode: '87546',
        },
        department: 'Sales',
    },
    {
        firstName: 'Sarah',
        lastName: 'Connor',
        birthDate: '6/25/1978',
        startDate: '3/12/1997',
        address: {
            street: 'Conway road, 7th',
            city: 'Birmingham',
            stateName: 'CA',
            zipCode: '78512',
        },
        department: 'Human Ressources',
    },
    {
        firstName: 'Didi',
        lastName: 'Coleman',
        birthDate: '9/18/1937',
        startDate: '10/26/1958',
        address: {
            street: 'Dust street',
            city: 'Washington',
            stateName: 'WT',
            zipCode: '12365',
        },
        department: 'Legal',
    },
]